@baseUrl = http://localhost:3000

### Read all users
GET {{baseUrl}}/users

### Insert a score
POST {{baseUrl}}/users/addScore
Content-Type: application/json

{
    "user":1,
    "score":3333
}


### get all player with the pseudo
GET {{baseUrl}}/users/getUser?pseudo=j

### get all friends
GET {{baseUrl}}/users/getUserFriends?id=1


### add a friend
POST {{baseUrl}}/users/addFriend
Content-Type: application/json

{
    "user1":1,
    "user2":5
}


# should all return error 
### add a friend
POST {{baseUrl}}/users/addFriend
Content-Type: application/json

{
    "user1":1,
    "user2":2
}

### add a friend
POST {{baseUrl}}/users/addFriend
Content-Type: application/json

{
    "user1":1,
    "user2":1
}

### add a friend

POST {{baseUrl}}/users/addFriend
Content-Type: application/json

{
    "user1":2,
    "user2":1
}





### add a user
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username":"Azard69",
    "password":"123"
}

### login a user known

POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username":"omar le j2",
    "password":"mdp2"
}

### login a user wrong password

POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username":"omar le j2",
    "password":"REAREZ"
}